## traefik.yml

log:
  level: DEBUG

# Docker configuration backend
providers:
  docker:
    network: traefik_webgateway
    exposedByDefault: false
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.localhost`)"
    endpoint: "unix:///var/run/docker.sock"

# API and dashboard configuration
api:
  insecure: true

accessLog:
  filePath: "/var/log/traefik/access.log"
